/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoAdminRouteImport } from './routes/demo-admin'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoutexRouteImport } from './routes/routex'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as RentalsIndexRouteImport } from './routes/rentals.index'
import { Route as RoutexIndexRouteImport } from './routes/routex.index'
import { Route as RoutexAnalyticsRouteImport } from './routes/routex.analytics'
import { Route as RoutexDeliveriesRouteImport } from './routes/routex.deliveries'
import { Route as RoutexDriversRouteImport } from './routes/routex.drivers'
import { Route as RoutexLiveMapRouteImport } from './routes/routex.live-map'
import { Route as RoutexRoutesRouteImport } from './routes/routex.routes'
import { Route as RoutexSettingsRouteImport } from './routes/routex.settings'
import { Route as RentalsCategoryIndexRouteImport } from './routes/rentals.$category.index'
import { Route as RentalsCategoryItemRouteImport } from './routes/rentals.$category.$item'
import { Route as RoutexRoutesIdRouteImport } from './routes/routex.routes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAdminRoute = DemoAdminRouteImport.update({
  id: '/demo-admin',
  path: '/demo-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutexRoute = RoutexRouteImport.update({
  id: '/routex',
  path: '/routex',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsIndexRoute = RentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutexIndexRoute = RoutexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutexRoute,
} as any)
const RoutexAnalyticsRoute = RoutexAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RoutexRoute,
} as any)
const RoutexDeliveriesRoute = RoutexDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => RoutexRoute,
} as any)
const RoutexDriversRoute = RoutexDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => RoutexRoute,
} as any)
const RoutexLiveMapRoute = RoutexLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => RoutexRoute,
} as any)
const RoutexRoutesRoute = RoutexRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => RoutexRoute,
} as any)
const RoutexSettingsRoute = RoutexSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RoutexRoute,
} as any)
const RentalsCategoryIndexRoute = RentalsCategoryIndexRouteImport.update({
  id: '/rentals/$category/',
  path: '/rentals/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsCategoryItemRoute = RentalsCategoryItemRouteImport.update({
  id: '/rentals/$category/$item',
  path: '/rentals/$category/$item',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutexRoutesIdRoute = RoutexRoutesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoutexRoutesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/demo-admin': typeof DemoAdminRoute
  '/faqs': typeof FaqsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/routex': typeof RoutexRouteWithChildren
  '/service-areas': typeof ServiceAreasRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/routex/analytics': typeof RoutexAnalyticsRoute
  '/routex/deliveries': typeof RoutexDeliveriesRoute
  '/routex/drivers': typeof RoutexDriversRoute
  '/routex/live-map': typeof RoutexLiveMapRoute
  '/routex/routes': typeof RoutexRoutesRouteWithChildren
  '/routex/settings': typeof RoutexSettingsRoute
  '/events/': typeof EventsIndexRoute
  '/rentals/': typeof RentalsIndexRoute
  '/routex/': typeof RoutexIndexRoute
  '/rentals/$category/$item': typeof RentalsCategoryItemRoute
  '/routex/routes/$id': typeof RoutexRoutesIdRoute
  '/rentals/$category/': typeof RentalsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/demo-admin': typeof DemoAdminRoute
  '/faqs': typeof FaqsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/service-areas': typeof ServiceAreasRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/routex/analytics': typeof RoutexAnalyticsRoute
  '/routex/deliveries': typeof RoutexDeliveriesRoute
  '/routex/drivers': typeof RoutexDriversRoute
  '/routex/live-map': typeof RoutexLiveMapRoute
  '/routex/routes': typeof RoutexRoutesRouteWithChildren
  '/routex/settings': typeof RoutexSettingsRoute
  '/events': typeof EventsIndexRoute
  '/rentals': typeof RentalsIndexRoute
  '/routex': typeof RoutexIndexRoute
  '/rentals/$category/$item': typeof RentalsCategoryItemRoute
  '/routex/routes/$id': typeof RoutexRoutesIdRoute
  '/rentals/$category': typeof RentalsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/demo-admin': typeof DemoAdminRoute
  '/faqs': typeof FaqsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/routex': typeof RoutexRouteWithChildren
  '/service-areas': typeof ServiceAreasRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/routex/analytics': typeof RoutexAnalyticsRoute
  '/routex/deliveries': typeof RoutexDeliveriesRoute
  '/routex/drivers': typeof RoutexDriversRoute
  '/routex/live-map': typeof RoutexLiveMapRoute
  '/routex/routes': typeof RoutexRoutesRouteWithChildren
  '/routex/settings': typeof RoutexSettingsRoute
  '/events/': typeof EventsIndexRoute
  '/rentals/': typeof RentalsIndexRoute
  '/routex/': typeof RoutexIndexRoute
  '/rentals/$category/$item': typeof RentalsCategoryItemRoute
  '/routex/routes/$id': typeof RoutexRoutesIdRoute
  '/rentals/$category/': typeof RentalsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/demo-admin'
    | '/faqs'
    | '/portal'
    | '/privacy'
    | '/routex'
    | '/service-areas'
    | '/terms'
    | '/events/$slug'
    | '/routex/analytics'
    | '/routex/deliveries'
    | '/routex/drivers'
    | '/routex/live-map'
    | '/routex/routes'
    | '/routex/settings'
    | '/events/'
    | '/rentals/'
    | '/routex/'
    | '/rentals/$category/$item'
    | '/routex/routes/$id'
    | '/rentals/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/demo-admin'
    | '/faqs'
    | '/portal'
    | '/privacy'
    | '/service-areas'
    | '/terms'
    | '/events/$slug'
    | '/routex/analytics'
    | '/routex/deliveries'
    | '/routex/drivers'
    | '/routex/live-map'
    | '/routex/routes'
    | '/routex/settings'
    | '/events'
    | '/rentals'
    | '/routex'
    | '/rentals/$category/$item'
    | '/routex/routes/$id'
    | '/rentals/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/demo-admin'
    | '/faqs'
    | '/portal'
    | '/privacy'
    | '/routex'
    | '/service-areas'
    | '/terms'
    | '/events/$slug'
    | '/routex/analytics'
    | '/routex/deliveries'
    | '/routex/drivers'
    | '/routex/live-map'
    | '/routex/routes'
    | '/routex/settings'
    | '/events/'
    | '/rentals/'
    | '/routex/'
    | '/rentals/$category/$item'
    | '/routex/routes/$id'
    | '/rentals/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DemoAdminRoute: typeof DemoAdminRoute
  FaqsRoute: typeof FaqsRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  RoutexRoute: typeof RoutexRouteWithChildren
  ServiceAreasRoute: typeof ServiceAreasRoute
  TermsRoute: typeof TermsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  RentalsIndexRoute: typeof RentalsIndexRoute
  RentalsCategoryItemRoute: typeof RentalsCategoryItemRoute
  RentalsCategoryIndexRoute: typeof RentalsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-admin': {
      id: '/demo-admin'
      path: '/demo-admin'
      fullPath: '/demo-admin'
      preLoaderRoute: typeof DemoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routex': {
      id: '/routex'
      path: '/routex'
      fullPath: '/routex'
      preLoaderRoute: typeof RoutexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/': {
      id: '/rentals/'
      path: '/rentals'
      fullPath: '/rentals/'
      preLoaderRoute: typeof RentalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routex/': {
      id: '/routex/'
      path: '/'
      fullPath: '/routex/'
      preLoaderRoute: typeof RoutexIndexRouteImport
      parentRoute: typeof RoutexRoute
    }
    '/routex/analytics': {
      id: '/routex/analytics'
      path: '/analytics'
      fullPath: '/routex/analytics'
      preLoaderRoute: typeof RoutexAnalyticsRouteImport
      parentRoute: typeof RoutexRoute
    }
    '/routex/deliveries': {
      id: '/routex/deliveries'
      path: '/deliveries'
      fullPath: '/routex/deliveries'
      preLoaderRoute: typeof RoutexDeliveriesRouteImport
      parentRoute: typeof RoutexRoute
    }
    '/routex/drivers': {
      id: '/routex/drivers'
      path: '/drivers'
      fullPath: '/routex/drivers'
      preLoaderRoute: typeof RoutexDriversRouteImport
      parentRoute: typeof RoutexRoute
    }
    '/routex/live-map': {
      id: '/routex/live-map'
      path: '/live-map'
      fullPath: '/routex/live-map'
      preLoaderRoute: typeof RoutexLiveMapRouteImport
      parentRoute: typeof RoutexRoute
    }
    '/routex/routes': {
      id: '/routex/routes'
      path: '/routes'
      fullPath: '/routex/routes'
      preLoaderRoute: typeof RoutexRoutesRouteImport
      parentRoute: typeof RoutexRoute
    }
    '/routex/settings': {
      id: '/routex/settings'
      path: '/settings'
      fullPath: '/routex/settings'
      preLoaderRoute: typeof RoutexSettingsRouteImport
      parentRoute: typeof RoutexRoute
    }
    '/rentals/$category/': {
      id: '/rentals/$category/'
      path: '/rentals/$category'
      fullPath: '/rentals/$category/'
      preLoaderRoute: typeof RentalsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$category/$item': {
      id: '/rentals/$category/$item'
      path: '/rentals/$category/$item'
      fullPath: '/rentals/$category/$item'
      preLoaderRoute: typeof RentalsCategoryItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routex/routes/$id': {
      id: '/routex/routes/$id'
      path: '/$id'
      fullPath: '/routex/routes/$id'
      preLoaderRoute: typeof RoutexRoutesIdRouteImport
      parentRoute: typeof RoutexRoutesRoute
    }
  }
}

interface RoutexRoutesRouteChildren {
  RoutexRoutesIdRoute: typeof RoutexRoutesIdRoute
}

const RoutexRoutesRouteChildren: RoutexRoutesRouteChildren = {
  RoutexRoutesIdRoute: RoutexRoutesIdRoute,
}

const RoutexRoutesRouteWithChildren = RoutexRoutesRoute._addFileChildren(
  RoutexRoutesRouteChildren,
)

interface RoutexRouteChildren {
  RoutexAnalyticsRoute: typeof RoutexAnalyticsRoute
  RoutexDeliveriesRoute: typeof RoutexDeliveriesRoute
  RoutexDriversRoute: typeof RoutexDriversRoute
  RoutexLiveMapRoute: typeof RoutexLiveMapRoute
  RoutexRoutesRoute: typeof RoutexRoutesRouteWithChildren
  RoutexSettingsRoute: typeof RoutexSettingsRoute
  RoutexIndexRoute: typeof RoutexIndexRoute
}

const RoutexRouteChildren: RoutexRouteChildren = {
  RoutexAnalyticsRoute: RoutexAnalyticsRoute,
  RoutexDeliveriesRoute: RoutexDeliveriesRoute,
  RoutexDriversRoute: RoutexDriversRoute,
  RoutexLiveMapRoute: RoutexLiveMapRoute,
  RoutexRoutesRoute: RoutexRoutesRouteWithChildren,
  RoutexSettingsRoute: RoutexSettingsRoute,
  RoutexIndexRoute: RoutexIndexRoute,
}

const RoutexRouteWithChildren =
  RoutexRoute._addFileChildren(RoutexRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DemoAdminRoute: DemoAdminRoute,
  FaqsRoute: FaqsRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  RoutexRoute: RoutexRouteWithChildren,
  ServiceAreasRoute: ServiceAreasRoute,
  TermsRoute: TermsRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  RentalsIndexRoute: RentalsIndexRoute,
  RentalsCategoryItemRoute: RentalsCategoryItemRoute,
  RentalsCategoryIndexRoute: RentalsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
